### ISSUE TITLE
Makefile make same executable files with different name.

### ISSUE THREAD

**Issue by jungingyo** [hybo-ilidar/api-demo#2] opened 2020-06-23 09:16 UTC
When I try to build the solution with **Makefile**, it makes three executable file (rdsensor, logsensor, and sensor2csv.exe). But the function of all three exe files is same; all three exe files act as like sensor2csv.

**Comment by hybo-ilidar** [comment] 2020-06-24 09:24
Fixed Makefile.  Further noted program `log sensor` is really not needed, it is almost a duplicate of `sensor2csv`. Removed it.

**Closed as completed by hybo-ilidar** 2020-06-24 09:24 UTC
